<?xml version="1.0" encoding="utf-8"?>
<!--
<!DOCTYPE etiqueta [
  <!ELEMENT etiqueta (nombre, calle, ciudad, pais, codigo)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT calle (#PCDATA)>
  <!ELEMENT ciudad (#PCDATA)>
  <!ELEMENT pais (#PCDATA)>
  <!ELEMENT codigo (#PCDATA)>
]>-->
<!DOCTYPE etiqueta SYSTEM "12.dtd">
<etiqueta>
  <nombre>Roberto García</nombre>
  <calle>c/ Mayor, 27</calle>
  <ciudad>Coslada</ciudad>
  <pais>España</pais>
  <codigo>39343</codigo>
</etiqueta>
